<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>

    <!-- Microsoft.Testing.Platform -->
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>

    <!-- xUnit v3 runner -->
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>

    <!-- MTP test projects must be executable -->
    <OutputType>Exe</OutputType>
    <UserSecretsId>c1a0f898-8e50-4ddf-958f-735e22d3aeec</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.11" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />

    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.0.4" />

    <PackageReference Include="FluentAssertions" Version="8.10.0" />

    <PackageReference Include="Testcontainers.MsSql" Version="4.14.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpportunityHub.Infrastructure.Persistence\OpportunityHub.Infrastructure.Persistence.csproj" />
  </ItemGroup>

</Project>